/**
 * Long-form writeups (~1000 words) for culture item details.
 * Use in seed-culture.js for curated items.
 */

module.exports = {
  Diwali: `Diwali, or Deepavali, is one of the most widely celebrated festivals in India and among Tamil communities worldwide. The name itself comes from the Sanskrit "dipavali," meaning "row of lights," and the festival is often called the festival of lights. For Tamils, Diwali holds deep cultural and religious significance, marking the triumph of light over darkness and good over evil.

On the morning of Diwali, Tamils traditionally begin the day with an oil bath, known in Tamil as ennaan kuli or abhyangasnanam. This is not a quick rinse but a full ritual: warm oil—often sesame or coconut—is applied to the scalp and body before bathing. The oil bath is believed to purify the body and soul and to symbolise the washing away of the previous year's troubles. Many families use a special herbal mix or scented oils passed down through generations. After the oil bath, people wear new clothes, another important custom that signifies a fresh start and prosperity for the coming year.

The home is then prepared for the evening. Oil lamps, or diyas, are lit in every corner of the house. In Tamil, a lamp is called a vilakku. These are typically small clay lamps filled with oil and a cotton wick, though today decorative and electric lights are also common. The idea is to drive away darkness and invite Lakshmi, the goddess of wealth and prosperity, into the home. In some traditions, every room is lit so that no shadow is left untouched. The sight of rows of flickering lamps is one of the most enduring images of Diwali.

Firecrackers, or pattasu in Tamil, are another familiar part of the celebration, especially for children. While their use has become controversial due to noise and pollution, the tradition of bursting crackers is linked to the belief that the sound drives away evil spirits. In Tamil Nadu, the scale of firecracker use can be enormous, with families competing to light the loudest or most colourful displays. In recent years, many households have shifted to "green" or reduced-noise crackers, or have given them up altogether in favour of a quieter, more reflective observance.

Food and sweets play a central role. Sweets in Tamil are called mittai or mithai, and no Diwali is complete without a variety of them. Families prepare or buy laddus, jalebis, murukku, and other savouries. These are first offered to the gods and ancestors, then shared with family, neighbours, and friends. The exchange of sweets and gifts, or parisu, strengthens bonds and is a way of wishing one another prosperity and happiness. A full meal, often vegetarian, is cooked at home and shared as a family. The emphasis on shared food and new clothes underscores the values of abundance, generosity, and togetherness.

The family, or kutumbam in Tamil, is at the heart of the celebration. Relatives who live elsewhere often travel to be together. The home, or veedu, is cleaned and decorated; entrances are marked with colourful kolams or rangoli. In the evening, after the lamps are lit and prayers are offered, everyone sits down to eat and enjoy each other's company. For many Tamils, Diwali is also a time to remember ancestors and to perform simple rites in their honour.

The religious meaning of Diwali varies by region and community. In the north, it is often associated with Lord Rama's return to Ayodhya after defeating Ravana; in the south, it is linked to Krishna's victory over Narakasura, and in some traditions to the goddess Lakshmi. Whatever the narrative, the common thread is the victory of light over darkness and the hope for a prosperous new year. Temples are crowded with devotees, and special pujas are conducted at home and in public spaces.

In Tamil Nadu, the days leading up to Diwali are busy. Markets are full of shoppers buying clothes, sweets, crackers, and decorations. Offices and schools close for the festival. On the day itself, the rhythm of the household is built around the oil bath, the lighting of lamps, the bursting of crackers, and the feast. For Tamils living outside India, Diwali is a way to stay connected to their roots; community events, temple celebrations, and family gatherings help keep the tradition alive.

Over the years, Diwali has also become a time for reflection. Many use the occasion to forgive old grievances, clear debts, and start the new year with a clean slate. The combination of ritual, food, family, and light makes Diwali a festival that appeals to the senses and the spirit alike. Whether celebrated in a village in Tamil Nadu or in a city abroad, the essence remains: light, gratitude, and the hope for a bright and prosperous year ahead.`,

  Pongal: `Pongal is Tamil Nadu's most beloved harvest festival, celebrated with joy and gratitude by farmers and city dwellers alike. The name "Pongal" refers both to the festival and to the sweet dish that is its centrepiece: rice cooked with milk and jaggery in a new clay pot until it boils over. That overflow is considered auspicious, symbolising abundance and prosperity for the year ahead.

The festival falls in the month of Thai (January–February) and typically spans four days. The first day, Bhogi, is dedicated to discarding the old: people clean their homes and burn unused items in a bonfire, marking a fresh start. The second day is Thai Pongal, the main day, when the sun is honoured and the Pongal dish is prepared at sunrise. The third day, Mattu Pongal, is for thanking cattle—cows and bulls who help in the fields are bathed, decorated, and fed. The fourth day, Kaanum Pongal, is for outings and visiting family and friends.

On Thai Pongal morning, families gather in the courtyard or at the entrance of the house. A new clay pot, often decorated with turmeric and leaves, is used to cook the Pongal. Rice, milk, and jaggery are added, and as the mixture boils and spills over, everyone shouts "Pongalo Pongal!"—a cry of joy and thanks. The dish is first offered to the sun god, then to the household deities, and finally shared among the family. The use of a new pot and the overflow are deliberate: they represent new beginnings and the hope that the harvest and life will overflow with plenty.

Kolam, or rangoli, is an essential part of the decoration. Women draw intricate patterns on the ground at the entrance of the house using rice flour or chalk. These designs are meant to welcome guests and the goddess Lakshmi, and to bring good fortune. In villages, the streets are lined with kolams, and the whole community takes part in the celebrations. The art of kolam is passed down through generations, with each region having its own style and motifs.

Agriculture and farming are at the heart of Pongal. Tamil Nadu has a long history of cultivation, and the festival is a way of thanking the land, the sun, the rain, and the animals that make farming possible. On Mattu Pongal, cattle are given a day of rest and respect: they are washed, their horns are painted, and they are fed Pongal and fruits. In some villages, bull races or other traditional games are held. The bond between the farmer and his animals is honoured, reflecting a way of life that has sustained Tamil society for centuries.

The ingredients of Pongal themselves carry meaning. Rice represents the staple crop and the fruit of the harvest. Milk symbolises purity and nourishment. Jaggery, or vellam in Tamil, adds sweetness and is a traditional unrefined sugar. Ghee is often added for richness. Together, the dish is both an offering and a feast, shared with relatives and neighbours. No Pongal is complete without a spread of other dishes: vadai, payasam, vegetables, and more.

For Tamils living outside Tamil Nadu, Pongal is a way to stay connected to their roots. Community associations organise events where people gather to cook Pongal, draw kolams, and celebrate. The festival is also an opportunity to teach the next generation about Tamil culture, the importance of the harvest, and the value of gratitude. In recent years, "Pongal in the Park" and similar events have become popular in cities like Chennai, where urbanites can experience a slice of village life.

The sun is central to the festival. Surya Pongal is the name given to the second day, when the sun is thanked for its role in the harvest. The belief is that the sun begins its northward journey on this day, bringing longer days and warmer weather—ideal for the next cropping season. Prayers are offered at sunrise, and the first offering of Pongal is made to the sun before anyone eats.

The house and the family are at the centre of the celebration. Homes are cleaned and decorated; new clothes are worn; and everyone, from the youngest to the oldest, takes part. The feast is a family affair, and the sharing of food strengthens bonds. In many households, the recipe for Pongal and the way kolam is drawn are family traditions, with each home adding its own touch.

Pongal is more than a festival; it is an expression of gratitude, community, and the enduring link between the Tamil people and the land. Whether in a village where the harvest is brought in or in a city where the festival is a reminder of one's heritage, the spirit of Pongal—thanksgiving, abundance, and togetherness—remains the same.`,
};
